name: Debug Build Step by Step

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Test basic environment
      run: |
        echo "✅ 基础环境正常"
        uname -a
        df -h
        echo "当前目录: $(pwd)"
        
    - name: Install dependencies with verification
      run: |
        sudo apt-get update
        echo "安装构建依赖..."
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev \
          zlib1g-dev gawk git gettext libssl-dev xsltproc wget unzip python3 python3-requests
        echo "✅ 依赖安装完成"
        
        # 验证关键工具
        which wget && echo "✅ wget 已安装" || echo "❌ wget 缺失"
        which tar && echo "✅ tar 已安装" || echo "❌ tar 缺失"
        which make && echo "✅ make 已安装" || echo "❌ make 缺失"
        
    - name: Test network connectivity
      run: |
        echo "测试网络连接..."
        timeout 10s ping -c 3 downloads.openwrt.org || echo "Ping 测试跳过"
        wget --spider --timeout=10 https://downloads.openwrt.org/ || echo "HTTPS 测试跳过"
        echo "网络测试完成"
        
    - name: Download ImageBuilder with retry
      run: |
        echo "开始下载 ImageBuilder..."
        for i in {1..3}; do
          echo "尝试第 $i 次下载..."
          if wget --timeout=60 --tries=3 https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz; then
            echo "✅ 下载成功"
            break
          else
            echo "❌ 下载失败，重试..."
            rm -f openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
            sleep 10
          fi
        done
        
        if [ ! -f "openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz" ]; then
          echo "❌ 所有下载尝试都失败"
          exit 1
        fi
        
        echo "文件大小: $(ls -lh openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz | awk '{print $5}')"
        
    - name: Extract and verify ImageBuilder
      run: |
        echo "解压 ImageBuilder..."
        tar -xf openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
        if [ $? -eq 0 ]; then
          echo "✅ 解压成功"
          cd openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64
          echo "目录内容:"
          ls -la
          echo "✅ ImageBuilder 准备完成"
        else
          echo "❌ 解压失败"
          exit 1
        fi
        
    - name: Test build system
      run: |
        cd openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64
        echo "测试构建系统..."
        make info
        echo "✅ 构建系统测试完成"
