name: Simple QoS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        
    - name: Download and build
      run: |
        wget https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
        tar -xf openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64.tar.xz
        cd openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64
        
        PROFILE=$(make info | grep "PROFILE_" | head -1 | cut -d'"' -f2)
        echo "使用设备: $PROFILE"
        
        # 只包含最基础的 QoS，避免复杂依赖
        make image PROFILE="$PROFILE" PACKAGES="luci luci-compat luci-app-qos"
        
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: simple-qos-firmware
        path: openwrt-imagebuilder-23.05.3-mediatek-filogic.Linux-x86_64/bin/targets/mediatek/filogic/*.bin
